### ISSUE TITLE
how to generate key frame?

### ISSUE THREAD

**Issue by ziyanxzy** [Deaddawn/MovieLLM-code#1]
in this repo, i just see the inference script for QA, but where can i use key frame generation function?

**Comment by Deaddawn** [comment]
Hi, we are currently working on a more easy-to-use code and will release the key frame generation code in this section **https://github.com/Deaddawn/MovieLLM-code?tab=readme-ov-file#pipeline**. You can check the raw data we just release.

**Comment by Deaddawn** [comment]
> in this repo, i just see the inference script for QA, but where can i use key frame generation function?

Hi, we are currently working on a more easy-to-use code and will release the key frame generation code in this section https://github.com/Deaddawn/MovieLLM-code?tab=readme-ov-file#pipeline. You can check the raw data we just release.

**Comment by ziyanxzy** [comment]
> > in this repo, i just see the inference script for QA, but where can i use key frame generation function?
> 
> Hi, we are currently working on a more easy-to-use code and will release the key frame generation code in this section https://github.com/Deaddawn/MovieLLM-code?tab=readme-ov-file#pipeline. You can check the raw data we just release.

thx. I am looking forward this function.
