### ISSUE TITLE
Which stable diffusion model do you use for  key frame generation?

### ISSUE THREAD

**Issue by lixingwen2007** [Deaddawn/MovieLLM-code#2]
Hi,thank you for your great job!I have read the paper ,but not find which verison of stable diffusion model do you use for key frame generation.Thank you !

**Comment by Deaddawn** [comment]
Hi, we use sdxl-1.0

**Comment by Deaddawn** [comment]
> Hi,thank you for your great job!I have read the paper ,but not find which verison of stable diffusion model do you use for key frame generation.Thank you !

Hi, we use sdxl-1.0
