### ISSUE TITLE
run_llamavid_movie_answer.py did not opensource, right?

### ISSUE THREAD

**Issue by ziyanxzy** [Deaddawn/MovieLLM-code#3]
![image](https://github.com/Deaddawn/MovieLLM-code/assets/109060006/279c1523-7027-4276-920d-4da50c7d5353)

**Comment by ziyanxzy** [comment]
and do you have movie original dataset (mp4 or avi), because the test_dataset only has pkl content. thank you

**Comment by SuperScavenger** [comment]
> ![image](https://private-user-images.githubusercontent.com/109060006/316400736-279c1523-7027-4276-920d-4da50c7d5353.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0MzExNDcsIm5iZiI6MTcxMTQzMDg0NywicGF0aCI6Ii8xMDkwNjAwMDYvMzE2NDAwNzM2LTI3OWMxNTIzLTcwMjctNDI3Ni05MjBkLTRkYTUwYzdkNTM1My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNlQwNTI3MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZWE5NWM2ZmJmZTYzNGFiYmQ3ZDMyZWZiNjE4YWFjN2RhZTAzNTQzODk2ODA4MDRiYTc0YmExY2NkODkyZWEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Y4Yl9OEb1eyEvLxVRi62vnvvWv9GP-O3Ku0hLoUVK10)

Hi, we have updated code, check it out.

**Comment by Deaddawn** [comment]
> ![image](https://private-user-images.githubusercontent.com/109060006/316400736-279c1523-7027-4276-920d-4da50c7d5353.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0MzU4MjEsIm5iZiI6MTcxMTQzNTUyMSwicGF0aCI6Ii8xMDkwNjAwMDYvMzE2NDAwNzM2LTI3OWMxNTIzLTcwMjctNDI3Ni05MjBkLTRkYTUwYzdkNTM1My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNlQwNjQ1MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZDYxMjA1M2VjYzEwMjczODg0MzcxMWFkZGM1OWNkMTJkYzhjMGZjNjM0YTk1YzM5OWI4ZDg3MzZjZmNkMDNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Gevtxyj2tl00ad0W117DNcGVMFLzDV62uBNjiugdjY0)

Hi, we have updated our code, check it out.
