### ISSUE TITLE
3090的显卡24G显存也跑不了

### ISSUE THREAD

**Issue by try2020-code** [Deaddawn/MovieLLM-code#6]
折腾了几天给部署上了。结果跑不了
![image](https://github.com/Deaddawn/MovieLLM-code/assets/84961646/53484cd6-0ebd-488d-a039-684835c7f734)

**Comment by Deaddawn** [comment]
> 折腾了几天给部署上了。结果跑不了 ![image](https://private-user-images.githubusercontent.com/84961646/330705730-53484cd6-0ebd-488d-a039-684835c7f734.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwMDUyOTUsIm5iZiI6MTcxNjAwNDk5NSwicGF0aCI6Ii84NDk2MTY0Ni8zMzA3MDU3MzAtNTM0ODRjZDYtMGViZC00ODhkLWEwMzktNjg0ODM1YzdmNzM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDA0MDMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4MjJmZDBkOWEzZjBkMTkwZGQ0MmRlMzY0NTFhYjhhOTQ0Nzg4MWI3MmRlODJjOGJlZmZmMGYwZWVhODBlYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tVZyNgAdIBRK9tWlEVJm6rVOoxCcYrdOWzNwxvybkZM)

Yes, we are currently unable to support 3090 following the same setting of LLAMA-VID which is mentioned in our manuscript.
